server {
    listen       80;
    server_name  localhost;

    gzip_static on;
    root   /usr/share/nginx/html;
    index  index.html;

    # Main application - handle SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /static {
        expires max;
    }

    location /signatures {
        expires 30d;
        default_type text/plain;
    }

    location /chains {
        expires 30d;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
    }
}